import { drizzle } from 'drizzle-orm/better-sqlite3';
import Database from 'better-sqlite3';
import * as schema from './schema.ts';

// Kanalernas kapabilitetsattribut - se docs/orkestreringssystem.md §2 och §6.
const channels: (typeof schema.channel.$inferInsert)[] = [
	{
		name: 'Airbnb',
		supportsPayment: true,
		contractCoverage: 'none',
		hasInsurance: false,
		handlesCleaning: false,
		syncType: 'ical',
		commissionRate: 0.155,
		notes:
			'iCal-only integration (no public API for standard hosts). Host-only fee model ' +
			'(~15.5%) is rolling out per-country during 2026; confirm Sweden status before relying on it.'
	},
	{
		name: 'Stugknuten',
		supportsPayment: true,
		contractCoverage: 'partial',
		hasInsurance: true,
		handlesCleaning: false,
		syncType: 'manual',
		commissionRate: 0.12,
		notes:
			'Guest pays in full via MangoPay at booking offer acceptance. Payout minus 12% ' +
			'commission arrives at earliest at checkout. Booking offer covers period/price/' +
			'payment/cancellation only - a separate terms addendum is required for house rules, ' +
			'damage liability, max guests, pets, smoking, cleaning. Omocom insurance included ' +
			'(1000 kr deductible, paid by host). Cleaning is not supported in their system.'
	},
	{
		name: 'Stugnet',
		supportsPayment: false,
		contractCoverage: 'none',
		hasInsurance: false,
		handlesCleaning: false,
		syncType: 'manual',
		commissionRate: 0,
		notes:
			'Free listing site with no booking engine, payment, calendar, or insurance - ' +
			"everything is the host's responsibility. Requires a full rental agreement, " +
			'booking confirmation, and deposit receipt generated by this system.'
	},
	{
		name: 'Fritiden',
		supportsPayment: false,
		contractCoverage: 'none',
		hasInsurance: false,
		handlesCleaning: false,
		syncType: 'manual',
		commissionRate: 0,
		notes:
			'380 kr/year listing fee, 0% commission, own payment (Swish/bank). Same profile as Stugnet.'
	}
];

const client = new Database(process.env.DATABASE_URL ?? 'local.db');
const db = drizzle(client, { schema });

for (const value of channels) {
	db.insert(schema.channel)
		.values(value)
		.onConflictDoUpdate({ target: schema.channel.name, set: value })
		.run();
}

console.log(`Seeded ${channels.length} channels.`);
